# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool: ANDREA

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'src/Trogsoft.CommandLine/Trogsoft.CommandLine.sln'
    arguments: '--no-restore /p:Configuration=Debug'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/Trogsoft.CommandLine/Trogsoft.CommandLine.Tests/Trogsoft.CommandLine.Tests.csproj'

- task: PowerShell@2
  inputs:
    filePath: 'version.ps1'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    configuration: 'Debug'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(VER)'
